export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const AUTH_CHECK = "AUTH_CHECK";

export const LOGOUT = "LOGOUT";

// 자기 id로 검색
export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";
export const GET_POST_LIST_FAILURE = "GET_POST_LIST_FAILURE";
// 저장된 post 검색
export const GET_SAVED_POST_LIST_SUCCESS = "GET_SAVED_POST_LIST_SUCCESS";
export const GET_SAVED_POST_LIST_FAILURE = "GET_SAVED_POST_LIST_FAILURE";
// 좋아요 개수 조회
export const GET_LIKE_COUNT_SUCCESS = "GET_LIKE_COUNT_SUCCESS";
export const GET_LIKE_COUNT_FAILURE = "GET_LIKE_COUNT_FAILURE";
// 좋아요
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";
// 좋아요 취소
export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAILURE = "UNLIKE_FAILURE";

//
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
